# Generated by Django 3.2 on 2025-02-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoLog',
        ),
    ]
